stages:
  - install
  - build
  - deploy

install:
  stage: install
  script:
    - curl -fsSL https://deb.nodesource.com/setup_20.11.1 | sudo -E bash - && sudo apt-get install -y nodejs

build:
  stage: build
  script:
    - cd client
    - npm install
    - npm run build
    - cd ..
    - cd server
    - npm install
    - npm run build

deploy:
  stage: deploy
  only:
    - dev # Trigger only on merges to the 'main' branch
    - main
  script:
    - scp -i $EC2_SSH_KEY client/* ubuntu@$EC2_IP_ADDRESS:/home/ubuntu/securaflow/client
    - scp -i $EC2_SSH_KEY server/* ubuntu@$EC2_IP_ADDRESS:/home/ubuntu/securaflow/server
    - ssh -i $EC2_SSH_KEY ubuntu@$EC2_IP_ADDRESS 'cd /home/ubuntu/securaflow/server && npm install && pm2 restart all && cd /home/ubuntu/securaflow/client && npm install'
